[package]
name = "wasp-input"
version = "0.1.0"
edition = "2021"
description = "wasp-input"

[lib]
name = "waspinput"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
retour = "0.3.1"
gl = "0.14"
windows = { version = "0.62", features = [
    "Win32_Security",
    "Win32_Foundation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_UI_Input",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Console",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_OpenGL"
]}
lazy_static = "1.4"