name: Notify WaspLib

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        env:
          TARGET_REPO: WaspScripts/wasp-plugins
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            https://api.github.com/repos/$TARGET_REPO/dispatches \
            -d "{\"event_type\": \"release-published\", \"client_payload\": {\"tag_name\": \"$TAG_NAME\"}}"
